MyProject/urls.py
from django.contrib import admin
from django.urls import path
from app_one.views import assets_views, depart_views, employee_views, permission_views, login_views

index_urlpatterns = [
    path('', depart_views.index, name="index"),
]

depart_urlpatterns = [
    path('depart/', depart_views.depart_list, name="depart_list"),
    path('depart/add/', depart_views.depart_add, name="depart_add"),
    path('depart/<int:nid>/modify/', depart_views.depart_modify, name="depart_modify"),
    path('depart/<int:nid>/del/', depart_views.depart_del, name="depart_del"),
]

employee_urlpatterns = [
    path('employee/', employee_views.employee_list, name="employee_list"),
    path('employee/add/modelform/', employee_views.user_add_modelform, name="user_add_modelform"),
    path('employee/<int:nid>/modify/', employee_views.user_modify_modelform, name="user_modify_modelform"),
    path('employee/<int:nid>/del/', employee_views.employee_del, name="employee_del"),
]

assets_urlpatterns = [
    path('assets/', assets_views.assets_list, name="assets_list"),
    path("assets/<int:nid>/del/", assets_views.assets_del, name="assets_del"),
    path('assets/add/modelform/', assets_views.assets_add_modelform, name="assets_add_modelform"),
    path('assets/<int:nid>/modify/modelform/', assets_views.assets_modify_modelform, name="assets_modify_modelform"),
    # path('assets/create/', assets_views.create_assets, name=""),
]

permission_urlpatterns = [
    path('permission/', permission_views.permission_list, name="permission_list"),
    path("permission/<int:nid>/del/", permission_views.permission_del, name="permission_del"),
    path('permission/add/', permission_views.permission_add, name="permission_add"),
    path('permission/<int:nid>/modify/', permission_views.permission_modify, name="permission_modify"),
    path('permission/<int:nid>/reset/', permission_views.permission_reset, name="permission_reset"),
    # path('permission/create/', assets_views.create_assets, name=""),
]

login_urlpatterns = [
    path('login/', login_views.login_views, name='login_views'),
    path('signup/', login_views.signup_views, name='signup'),  # 新增 signup 路由
]

urlpatterns =  [
    *index_urlpatterns,
    *depart_urlpatterns,
    *employee_urlpatterns,
    *assets_urlpatterns,
    *permission_urlpatterns,
    *login_urlpatterns,
    ]

app_one/models.py
from django.db import models

# Create your models here.
# department table
class Department(models.Model):
    title = models.CharField(verbose_name="department name", max_length=128)

    def __str__(self):
        return self.title

# employee table
class Employee(models.Model):
    name = models.CharField(verbose_name="name", max_length=32)
    age = models.IntegerField(verbose_name="age")
    gender_choice = (
        (1, "Male"),
        (2, "Female")
    )
    gender = models.SmallIntegerField(verbose_name="gender", choices=gender_choice)
    salary = models.CharField(verbose_name="salary", max_length=32)
    create_time = models.DateField(verbose_name="employed date")
    department = models.ForeignKey(verbose_name="department", 
                                   to="Department", 
                                   to_field="id", 
                                   on_delete=models.SET_NULL, 
                                   null=True, 
                                   blank=True
                                   )
    
    def __str__(self):
        return self.name


class Assets(models.Model):
    phone_num = models.CharField(verbose_name="Phone_num", max_length=11)
    start_code_choice = (
        (1, "has_been_occupied"),
        (2, "not_been_occupied")
    )
    status = models.IntegerField(verbose_name="Usage_condition", choices=start_code_choice)
    create_time = models.DateField(verbose_name="Created_time")
    user = models.ForeignKey(verbose_name="username",
                             to="Employee", 
                             to_field="id", 
                             on_delete=models.SET_NULL, 
                             null=True, 
                             blank=True
                             )
    price = models.CharField(verbose_name="Price", max_length=64)


class Permission(models.Model):
    username = models.CharField(verbose_name="username", max_length=32)
    password = models.CharField(verbose_name="password", max_length=64)
    ROLE_CHOICES = (
        (0, "Visitor"),
        (1, "User"),
        (2, "Root")
    )
    role = models.IntegerField(verbose_name="role", choices=ROLE_CHOICES)

app_one/views/assets_views.py
from django.core.validators import RegexValidator

from django.core.exceptions import ValidationError

from django.utils.safestring import mark_safe

from app_one.utils.page_data import PageData
from django.http import HttpResponse
from django .shortcuts import redirect, render
from django import forms
from app_one import models

from datetime import datetime
import random

def assets_list(request):
    # dict_data = {"mobile": "what I want to search"}
    dict_data = {}
    # access info in seacrch block
    phone_num_search = request.GET.get("search_phone_num")
    status_search = request.GET.get("search_status")

    if phone_num_search is not None:
        # search data with string in "value"
        dict_data["phone_num__contains"] = phone_num_search

    if status_search is not None:
        # search data with string in "value"
        dict_data["status__contains"] = status_search
    
    queryset = models.Assets.objects.filter(**dict_data)
    asset_page_object = PageData(request=request, 
                           queryset=queryset,
                           page_size=10
                           )
    
    dict_data_list = {
        "data_asset_list": asset_page_object.get_queryset(),
        "page_html": asset_page_object.get_pagehtml()
        }

    return render(request, "assets/asset_list.html", dict_data_list)

class AssetsModelForm(forms.ModelForm):
    phone_num = forms.CharField(
        label="phone_num",
        validators=[RegexValidator(r"^1[3-9]\d{9}", "Please input valid phone num")]
    )
    # # no edit
    # price = forms.CharField(disabled=True, label="price")

    class Meta:
        model = models.Assets
        fields = "__all__"
    
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for name, field in self.fields.items():
            field.widget.attrs = {
                "class": "form-control"
            }
    
    def clean_phone_num(self): 
        new_phone_num = self.cleaned_data["phone_num"]
        
        # 获取当前实例（如果有的话）
        instance = getattr(self, 'instance', None)

        # 检查新输入的 phone_num 是否已存在
        if_exists = models.Assets.objects.filter(phone_num=new_phone_num).exists()
        if if_exists and instance.phone_num != new_phone_num:
            raise ValidationError("phone# exists")
        
        return new_phone_num

    def __str__(self):
        return super().__str__()


# add information
def assets_add_modelform(request):
    if request.method == "GET":
        content = {
            "form": AssetsModelForm(),
            "title": "KISS add assets"
        }

        return render(request, "assets/asset_modify.html", content)
    
    # accept data from sheet
    form = AssetsModelForm(data=request.POST)
    # validate if data is valid
    if form.is_valid():
        #  store into database
        form.save()
        return redirect("/assets/")
    
    # if data is invalid
    # 1. back to original page
    # 2. show error info
    return render(request, "assets/asset_modify.html", {"form": form})


# modify information
def assets_modify_modelform(request, nid):
    data_list=  models.Assets.objects.filter(id=nid).first()
    title = "KISS add info"
    if request.method == "GET":
        content = {
            "form": AssetsModelForm(instance=data_list),
            "title": title
        }

        return render(request, "assets/asset_modify.html", content)
    
    # accept data from sheet
    form = AssetsModelForm(data=request.POST, instance=data_list)
    # validate if data is valid
    if form.is_valid():
        #  store into database
        form.save()
        return redirect("/assets/")
    
    # if data is invalid
    return render(request, "assets/asset_modify.html", {"form": form, "title": title})

# MID-page to add Employees
def assets_del(request, nid):
    models.Assets.objects.filter(id=nid).delete()
    return redirect("/assets/")

def create_assets(request):
    for _ in range(200):
        phone_num = "133" + str(random.randint(10000000, 99999999))
        
        status = random.randint(1,2)

        now = datetime.now()
        create_time = now.strftime("%Y-%m-%d")
        
        price = random.randint(5000, 7000)
        
        user_id = random.randint(2, 5)
        try:
            print(phone_num, status, create_time, price, user_id)
            models.Assets.objects.create(
                phone_num=phone_num,
                status=status,
                create_time=create_time,
                price=price,
                user_id=user_id,
            )
        except ValidationError:
            print("replicates")
            continue
    return redirect("/assets/")

app_one/views/depart_views.py
from django.shortcuts import redirect, render
from app_one import models
from app_one.utils.page_data import PageData

# index page (main page)
def index(request):
    return render(request, "index/index.html") 

# page showing information about departments
def depart_list(request):
    queryset = models.Department.objects.all()
    page_object = PageData(request=request, 
                           queryset=queryset,
                           page_size=10,
                           edge=1
                           )

    dict_data_list = {
        "data_list": page_object.get_queryset(),
        "page_html": page_object.get_pagehtml()
        }

    return render(request, "depart/depart_list.html", dict_data_list)

# page to add departments
def depart_add(request):
    if request.method == "GET":
        title = "Add info"
        return render(request, "depart/depart_edit.html", {'title':title})
    title = request.POST.get("title")
    models.Department.objects.create(title=title)
    return redirect("/depart/")

# MID-page to add departments
def depart_del(request, nid):
    models.Department.objects.filter(id=nid).delete()
    return redirect("/depart/")

# MID-page to add departments
def depart_modify(request, nid):
    if request.method == "GET":
        title = "Modify info"
        name = models.Department.objects.filter(id=nid).first()
        return render(request, 
                      "depart/depart_edit.html", 
                      {'title':title, 'name':name}
                      )
    title = request.POST.get("title")
    models.Department.objects.filter(id=nid).update(title=title)
    return redirect('/depart/')

app_one/views/employee_views.py
from django.shortcuts import redirect, render
from app_one import models
from app_one.utils.page_data import PageData
from django import forms

# page showing information about Employees
def employee_list(request):
    queryset = models.Employee.objects.all()
    page_object = PageData(request=request, 
                           queryset=queryset,
                           page_size=2,
                           edge=1
                           )

    dict_data_list = {
        "data_list": page_object.get_queryset(),
        "page_html": page_object.get_pagehtml()
        }

    return render(request, "employee/employee_list.html", dict_data_list)

# MID-page to add Employees
def employee_del(request, nid):
    models.Employee.objects.filter(id=nid).delete()
    return redirect("/employee/")

# ModelForm
class EmployeeModelForm(forms.ModelForm):
    name = forms.CharField(min_length=2, label="name")

    # extra appended Field
    class Meta:
        model = models.Employee
        #  read Field in sheet
        fields = "__all__"
    
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for name, field in self.fields.items():
            field.widget.attrs = {
                "class": "form-control"
            }
    
    def __str__(self):
        return super().__str__()
        

def user_add_modelform(request):
    if request.method == "GET":
        content = {
            "form": EmployeeModelForm(),
            "title": "KISS add info"
        }

        return render(request, "employee/employee_modify.html", content)
    
    # accept data from sheet
    form = EmployeeModelForm(data=request.POST)
    # validate if data is valid
    if form.is_valid():
        #  store into database
        form.save()
        return redirect("/employee/")
    
    # if data is invalid
    # 1. back to original page
    # 2. show error info
    return render(request, "employee/employee_modify.html", {"form": form})



def user_modify_modelform(request, nid):
    obj = models.Employee.objects.filter(id=nid).first()
    if request.method == "GET":
        form = EmployeeModelForm(instance=obj)
        title = "KISS modify info"
        content = {
            "form": form,
            "title": title
        }
        return render(request, "employee/employee_modify.html", content)
    
    # accept data from sheet
    form = EmployeeModelForm(data=request.POST, instance=obj)
    # validate if data is valid
    if form.is_valid():
        #  store into database
        form.save()
        return redirect("/employee/")
    

app_one/views/login_views.py
from django.shortcuts import render, redirect
from app_one.utils import pwd_encrypt
from app_one import models
from django.contrib.auth import authenticate, login, get_user_model
from django import forms


# 登录表单
class LoginForm(forms.Form):
    def clean_password(self):
        pwd = self.cleaned_data.get("password")
        return pwd_encrypt.md5(pwd)


    username = forms.CharField(
        label="username",
        max_length=100,
        widget=forms.TextInput(attrs={'label':'username', 'class': 'form-control', 'placeholder': '请输入用户名'})
    )
    password = forms.CharField(
        label="password",
        widget=forms.PasswordInput(attrs={'label': 'password', 'class': 'form-control', 'placeholder': '请输入密码'})
    )


# 注册表单
class RegisterForm(forms.Form):
    username = forms.CharField(
        label="用户名",
        max_length=100,
        widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': '请输入用户名'})
    )
    password1 = forms.CharField(
        label="密码",
        widget=forms.PasswordInput(attrs={'class': 'form-control', 'placeholder': '请输入密码'})
    )
    password2 = forms.CharField(
        label="确认密码",
        widget=forms.PasswordInput(attrs={'class': 'form-control', 'placeholder': '请再次输入密码'})
    )

    def clean(self):
        cleaned_data = super().clean()
        password1 = cleaned_data.get("password1")
        password2 = cleaned_data.get("password2")
        if password1 and password2 and password1 != password2:
            raise forms.ValidationError("两次输入的密码不一致")
        return cleaned_data

# 登录视图
def login_views(request):
    if request.method == "GET":
        form = LoginForm()
        return render(request, "login/login.html", {"form": form})
    
    form = LoginForm(data=request.POST)
    if form.is_valid():
        admin_object = models.Permission.objects.filter(**form.cleaned_data).first()
        if not admin_object:
            form.add_error("password", "wrong username or password")
            return render(request, "login/login.html", {"form": form})

        request.session["info"] = {"id":admin_object.id, 
                                   "username":admin_object.username, 
                                   "password":admin_object.password, 
                                   "role":admin_object.role
                                   }
        
        request.session.set_expiry(60)

        return redirect("/")
    
    return render(request, "login/login.html", {"form": form})

# 注册视图
def signup_views(request):
    if request.method == "GET":
        form = RegisterForm()
        return render(request, "login/register.html", {"form": form})
    
    form = RegisterForm(request.POST)
    if form.is_valid():
        username = form.cleaned_data["username"]
        password = form.cleaned_data["password1"]
        User = get_user_model()
        if User.objects.filter(username=username).exists():
            form.add_error("username", "该用户名已被占用")
        else:
            user = User.objects.create_user(username=username, password=password)
            login(request, user)
            return redirect("/")
    return render(request, "login/register.html", {"form": form})

app_one/templates/permission/permission_list.html
{% extends "index/template.html" %}

{% block css %}
{% endblock%}


{% block content %}
<div class="container">
    <!-- card -->
    <div class="card text-bg-dark mb-3">
        <div class="card-header">Permission info of Navbar</div>
        <div class="card-body">
            <h5 class="card-title">
                Permission table
                <!-- add info button -->
                <a href="/permission/add/" class="btn btn-warning" style="height: auto;width: auto;">Add</a>
            </h5>
            <table class="table">
                <thead>
                    <tr>
                        <th scope="col">ID</th>
                        <th scope="col">username</th>
                        <th scope="col">Password</th>
                        <th scope="col">Forgot_Password</th>
                        <th scope="col">Role</th>
                        <th scope="col">Operations</th>
                    </tr>
                </thead>
                <tbody>
                    {% for data in data_list %}
                        <tr>
                            {% comment %} id {% endcomment %}
                            <th scope="row">{{ data.id }}</th>

                            {% comment %} name {% endcomment %}
                            <td>{{ data.username }}</td>
                            
                            {% comment %} age {% endcomment %}
                            <td>{{ data.password }}</td>

                            {% comment %}  {% endcomment %}
                            <td><a href="/permission/{{ data.id }}/reset/">reset_password</a></td>
                            
                            {% comment %} gender {% endcomment %}
                            <td>{{ data.get_role_display }}</td>

                            <th>
                                {% comment %} edit {% endcomment %}
                                <a href="/permission/{{ data.id }}/modify/" style="text-decoration: none; color: green;">
                                    <span>
                                        <svg viewBox="0 0 24 24" width="24" height="24" stroke="currentColor" stroke-width="2" fill="none" stroke-linecap="round" stroke-linejoin="round" class="css-i6dzq1"><path d="M14.7 6.3a1 1 0 0 0 0 1.4l1.6 1.6a1 1 0 0 0 1.4 0l3.77-3.77a6 6 0 0 1-7.94 7.94l-6.91 6.91a2.12 2.12 0 0 1-3-3l6.91-6.91a6 6 0 0 1 7.94-7.94l-3.76 3.76z"></path></svg>
                                    </span>
                                </a>
                                {% comment %} delete {% endcomment %}
                                <a href="/permission/{{ data.id }}/del/" style="text-decoration: none; color: red;">
                                    <span>
                                        <svg viewBox="0 0 24 24" width="24" height="24" stroke="currentColor" stroke-width="2" fill="none" stroke-linecap="round" stroke-linejoin="round" class="css-i6dzq1"><polyline points="3 6 5 6 21 6"></polyline><path d="M19 6v14a2 2 0 0 1-2 2H7a2 2 0 0 1-2-2V6m3 0V4a2 2 0 0 1 2-2h4a2 2 0 0 1 2 2v2"></path></svg>
                                    </span>
                                </a>
                            </th>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>

            <nav aria-label="Page navigation example">
                <div class="d-flex align-items-center">
                    <ul class="pagination me-2">
                        {{ page_html }}                       
                    </ul>
                </div>
            </nav>

        </div>
    </div>
</div>
{% endblock%}

app_one/templates/permission/permission_modify.html
{% extends "index/template.html" %}
{% load static %}


{% block css %}
<link rel="stylesheet" href="{% static 'css/layui.css'%}">
{% endblock %}


{% block content %}
<div class="container">
    <!-- card -->
    <div class="card text-bg-dark mb-3">
        <div class="card-body row">
            <div class="col-2"></div>
            <div class="form-group col-8">
                <div class="card-header", style="font-size: 30pt;">
                    {{ title }}
                </div>
                <h5>fill the box, and click submit to add</h5>
                <form method="post" novalidate>
                    {% csrf_token %}
                    <!-- input -->
                    {% for filed in form %}
                    <div class="input-group mb-3">
                        <span class="input-group-text" id="inputGroup-sizing-default">{{ filed.label }}</span>
                        {{ filed }}
                    </div>
                    <div style="color:red"> {{ filed.errors }} </div>
                    {% endfor %}
                    <button type="submit" class="btn btn-success" style="font-size: large; margin-top: 10px;">
                        Submit
                    </button>
                </form>
            </div>
            <div class="col-2"></div>
        </div>
    </div>
</div>
{% endblock%}

{% block js %}
<script src="{% static 'js/layui.js' %}"></script>
<script>
    layui.use(function(){
        var laydate = layui.laydate;
        laydate.render({
          elem: '#id_create_time',
          lang: 'en'
        });
      });
</script>
{% endblock %}